# Generated by Django 5.0 on 2025-11-11 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('experience_required', models.CharField(max_length=100)),
                ('education_required', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_skills', models.TextField(blank=True)),
                ('extracted_experience', models.TextField(blank=True)),
                ('extracted_education', models.TextField(blank=True)),
                ('match_score', models.FloatField(default=0.0)),
                ('skills_match_score', models.FloatField(default=0.0)),
                ('experience_match_score', models.FloatField(default=0.0)),
                ('education_match_score', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='screener.jobdescription')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_resumes', models.IntegerField(default=0)),
                ('shortlisted_count', models.IntegerField(default=0)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.jobdescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
